### ISSUE TITLE
bugg (java.lagg.string)

### ISSUE THREAD

**Issue by amboris** [inorichi/tachiyomi#1070]
"attempt to invoke virtual method 'java.lag.string org.jsoup.nodes.Node.attr(java.lang.String)' on a null object reference"

This message pops up and it refuse to open any mangas doesnt matter with one I try. restart and and clear cookies doesnt help.

**Comment by j2ghz** [comment]
Wiki > Source Problems

**Comment by amboris** [comment]
I am a normal user, so that doesnt help me. rather than beeing a wiseacre you could explain or give a fix. 
Not all github user are tech pros. some of us just want to help making this app better by reporting issues.

**Comment by j2ghz** [comment]
I was on my phone and didn't have time to go looking for the url. Here it is https://github.com/inorichi/tachiyomi/wiki/Source-problems

For future reference: https://i.imgur.com/srqTwgE.png https://i.imgur.com/EtrooFF.png

**Comment by inorichi** [comment]
You should provide any relevant information if you want help. Like the version where it happens, catalogue that triggers the error, device (although this one shouldn't be relevant in this case)...

**Comment by kiskae491** [comment]
The same thing happens to me on v0.6.3. Looks like its only on readmanga.today, in browser everything works fine.
Where do I check versions of extension catalogues and how to update it? Almost all my mangas are added form readmanga (200+)

**Comment by j2ghz** [comment]
Did you get it through F-Droid? If yes, go to F-Droid to check for updates. https://github.com/inorichi/tachiyomi-extensions#readme

**Comment by na-ji** [comment]
Hey !
Here is the stacktrace : 
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Node.attr(java.lang.String)' on a null object reference
    at eu.kanade.tachiyomi.source.online.english.Readmangatoday.imageUrlParse(Readmangatoday.kt:164)
    at eu.kanade.tachiyomi.source.online.english.Readmangatoday.pageListParse(Readmangatoday.kt:160)
    at eu.kanade.tachiyomi.source.online.ParsedHttpSource.pageListParse(ParsedHttpSource.kt:175)
    at eu.kanade.tachiyomi.source.online.HttpSource$fetchPageList$1.call(HttpSource.kt:243)
    at eu.kanade.tachiyomi.source.online.HttpSource$fetchPageList$1.call(HttpSource.kt:24)
    at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
    at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:101)
    at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:25)
    at rx.internal.producers.ProducerArbiter.setProducer(ProducerArbiter.java:126)
    at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4$1.setProducer(OperatorOnErrorResumeNextViaFunction.java:130)
    at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
    at rx.Subscriber.setProducer(Subscriber.java:205)
    at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1.call(OkHttpExtensions.kt:45)
    at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1.call(OkHttpExtensions.kt:13)
    at rx.Observable.unsafeSubscribe(Observable.java:10256)
    at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
    at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
    at rx.Observable.unsafeSubscribe(Observable.java:10256)
    at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
    at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
    at rx.Observable.unsafeSubscribe(Observable.java:10256)
    at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:142)
    at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:212)
    at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:50)
    at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.Observable.unsafeSubscribe(Observable.java:10256)
    at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:235)
    at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:228)
    at rx.Observable.unsafeSubscribe(Observable.java:10256)
    at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
    at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
    at rx.Observable.unsafeSubscribe(Observable.java:10256)
    at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:235)
    at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:228)
    at rx.Observable.unsafeSubscribe(Observable.java:10256)
    at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
    at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
    at rx.Observable.unsafeSubscribe(Observable.java:10256)
    at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
    at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
    at rx.Observable.unsafeSubscribe(Observable.java:10256)
    at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
    at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:761)
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: okhttp3.Response.class
    at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)
	... 46 more
```

ReadmangaToday changed the class for the image in their reader. I will create a PR soon. 
@inorichi I presume I have to create a PR here and on https://github.com/inorichi/tachiyomi-extensions
Also, to not wait the next release, if I install readmangatoday as a standalone, it will use standalone or the built-in parser?

**Comment by j2ghz** [comment]
@na-ji If you install extension, it will be preferred over built-in. Create PR's on both.

**Comment by na-ji** [comment]
To fix this problem, three options are available:
 - Wait for the next stable release of Tachiyomi
 - Use the dev version of Tachiyomi
 - [Download Readmangatoday as an extension from F-Droid](https://github.com/inorichi/tachiyomi-extensions#usage)
