### ISSUE TITLE
Automatic backups still not working correctly

### ISSUE THREAD

**Issue by tippl** [inorichi/tachiyomi#1245]
There has been talk in #900 about backups not working correctly. Which has been apparently fixed for the people filing that issue.

For me however there have been rare times the backup actually occurs. When it was fixed there has been a backup once every few days despite having it set to every 6 hours. Since new year it is not backing up at all, date of my last automatic backup is 12. 12. 2017. Since then nothing.

Since i had 5 backups in the backup folder i thought it might be a problem with deleting old backups, but after deleting the 3 oldest to make space nothing changed.

Since it has been fixed for people with older android version it might be an issue with the new android background execution limits in 8.0+.

Version: 0.6.8
Phone: Pixel 2
Android: 8.1.0 OPM1.171019.013

**Comment by tippl** [comment]
Did some testing. Loaded up a virtual machine for android 7.1.1 and 8.1.0 and set up Tachiyomi same way on both devices.

Running `dumpsys jobscheduler` on both devices shows there is a job scheduled for backup, however forcing the execution of the job has different results on both devices.

7.1.1
```
-2m48s640ms START: u0a84 eu.kanade.tachiyomi/com.evernote.android.job.v21.PlatformJobService
-2m48s613ms  STOP: u0a84 eu.kanade.tachiyomi/com.evernote.android.job.v21.PlatformJobService
```
This simply shows the job start/end, backup works and there is a json file in the backup directory.

8.1.0
```
-14s930ms START-P: #u0a173/10 eu.kanade.tachiyomi/com.evernote.android.job.v21.PlatformJobService
-14s797ms   START: #u0a173/2147480000 eu.kanade.tachiyomi/com.evernote.android.job.JobRescheduleService
-14s748ms    STOP: #u0a173/10 eu.kanade.tachiyomi/com.evernote.android.job.v21.PlatformJobService canceled
-11s718ms  STOP-P: #u0a173/2147480000 eu.kanade.tachiyomi/com.evernote.android.job.JobRescheduleService canceled
```

This either shows up with or without the RescheduleService, but job is always shown as cancelled and there is no backup, nor a backup folder.

logcat for the backup service:
```02-12 05:58:38.356  1104 21507 I ActivityManager: Start proc 2234:eu.kanade.tachiyomi/u0a173 for service eu.kanade.tachiyomi/com.evernote.android.job.v21.PlatformJobService
02-12 05:58:38.478  2234  2234 I ACRA    : ACRA is enabled for eu.kanade.tachiyomi, initializing...
02-12 05:58:38.525  2234  2255 D PlatformJobService: Run job, request{id=10, tag=BackupCreator, transient=false}, waited 05:59:27, interval 06:00:00, flex 00:10:00
02-12 05:58:38.527  2234  2255 I JobExecutor: Executing request{id=10, tag=BackupCreator, transient=false}, context PlatformJobService
02-12 05:58:38.534  1104  5943 W ActivityManager: Background start not allowed: service Intent { cmp=eu.kanade.tachiyomi/.data.backup.BackupCreateService (has extras) } to eu.kanade.tachiyomi/.data.backup.BackupCreateService from pid=2234 uid=10173 pkg=eu.kanade.tachiyomi
02-12 05:58:38.536  2234  2257 E JobExecutor: Crashed job{id=10, finished=true, result=FAILURE, canceled=false, periodic=true, class=BackupCreatorJob, tag=BackupCreator}
02-12 05:58:38.536  2234  2257 E JobExecutor: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=eu.kanade.tachiyomi/.data.backup.BackupCreateService (has extras) }: app is in background uid UidRecord{7e9c51 u0a173 TRNB idle change:idle|uncached procs:1 seq(0,0,0)}
02-12 05:58:38.536  2234  2257 E JobExecutor: 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
02-12 05:58:38.536  2234  2257 E JobExecutor: 	at android.app.ContextImpl.startService(ContextImpl.java:1477)
02-12 05:58:38.536  2234  2257 E JobExecutor: 	at android.content.ContextWrapper.startService(ContextWrapper.java:650)
02-12 05:58:38.536  2234  2257 E JobExecutor: 	at eu.kanade.tachiyomi.data.backup.BackupCreateService$Companion.makeBackup(BackupCreateService.kt:59)
02-12 05:58:38.536  2234  2257 E JobExecutor: 	at eu.kanade.tachiyomi.data.backup.BackupCreatorJob.onRunJob(BackupCreatorJob.kt:18)
02-12 05:58:38.536  2234  2257 E JobExecutor: 	at com.evernote.android.job.Job.runJob(Job.java:120)
02-12 05:58:38.536  2234  2257 E JobExecutor: 	at com.evernote.android.job.JobExecutor$JobCallable.runJob(JobExecutor.java:191)
02-12 05:58:38.536  2234  2257 E JobExecutor: 	at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:176)
02-12 05:58:38.536  2234  2257 E JobExecutor: 	at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:159)
02-12 05:58:38.536  2234  2257 E JobExecutor: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02-12 05:58:38.536  2234  2257 E JobExecutor: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
02-12 05:58:38.536  2234  2257 E JobExecutor: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
02-12 05:58:38.536  2234  2257 E JobExecutor: 	at java.lang.Thread.run(Thread.java:764)
02-12 05:58:38.537  2234  2255 D PlatformJobService: Finished job, request{id=10, tag=BackupCreator, transient=false} FAILURE
```

Weird thing is on my phone though. Since the issue is about when you can run a service on 8.0+ i tried forcing the job with app open. Virtual machine works as expected and backup is created. My phone however outputs this.

```
02-12 06:19:36.394  3005  3365 D PlatformJobService: Run job, request{id=10, tag=BackupCreator, transient=false}, waited 06:20:25, interval 06:00:00, flex 00:10:00
02-12 06:19:36.394  3005  3365 I JobExecutor: Executing request{id=10, tag=BackupCreator, transient=false}, context PlatformJobService
02-12 06:19:36.408  3005  3366 I JobExecutor: Finished job{id=10, finished=true, result=SUCCESS, canceled=false, periodic=true, class=BackupCreatorJob, tag=BackupCreator}
02-12 06:19:36.431  3005  3365 D PlatformJobService: Finished job, request{id=10, tag=BackupCreator, transient=false} SUCCESS
02-12 06:19:36.802  2676  2690 E DatabaseUtils: Writing exception to parcel
02-12 06:19:36.802  2676  2690 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading com.android.externalstorage.ExternalStorageProvider uri content://com.android.externalstorage.documents/tree/primary%3ATachiyomi%2Fbackup/document/primary%3ATachiyomi%2Fbackup from pid=3005, uid=10173 requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
02-12 06:19:36.802  2676  2690 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:631)
02-12 06:19:36.802  2676  2690 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:501)
02-12 06:19:36.802  2676  2690 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:213)
02-12 06:19:36.802  2676  2690 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:102)
02-12 06:19:36.802  2676  2690 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:697)
02-12 06:19:36.803  2676  2690 E DatabaseUtils: Writing exception to parcel
02-12 06:19:36.803  2676  2690 E DatabaseUtils: java.lang.SecurityException: Permission Denial: writing com.android.externalstorage.ExternalStorageProvider uri content://com.android.externalstorage.documents/tree/primary%3ATachiyomi%2Fbackup/document/primary%3ATachiyomi%2Fbackup from pid=3005, uid=10173 requires android.permission.MANAGE_DOCUMENTS, or grantUriPermission()
02-12 06:19:36.803  2676  2690 E DatabaseUtils: 	at android.content.ContentProvider.enforceWritePermissionInner(ContentProvider.java:705)
02-12 06:19:36.803  2676  2690 E DatabaseUtils: 	at android.provider.DocumentsProvider.callUnchecked(DocumentsProvider.java:999)
02-12 06:19:36.803  2676  2690 E DatabaseUtils: 	at android.provider.DocumentsProvider.call(DocumentsProvider.java:949)
02-12 06:19:36.803  2676  2690 E DatabaseUtils: 	at com.android.externalstorage.ExternalStorageProvider.call(ExternalStorageProvider.java:543)
02-12 06:19:36.803  2676  2690 E DatabaseUtils: 	at android.content.ContentProvider$Transport.call(ContentProvider.java:401)
02-12 06:19:36.803  2676  2690 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:272)
02-12 06:19:36.803  2676  2690 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:697)
02-12 06:19:36.803  3005  3367 W DocumentsContract: Failed to create document
02-12 06:19:36.803  3005  3367 W DocumentsContract: java.lang.SecurityException: Permission Denial: writing com.android.externalstorage.ExternalStorageProvider uri content://com.android.externalstorage.documents/tree/primary%3ATachiyomi%2Fbackup/document/primary%3ATachiyomi%2Fbackup from pid=3005, uid=10173 requires android.permission.MANAGE_DOCUMENTS, or grantUriPermission()
02-12 06:19:36.803  3005  3367 W DocumentsContract: 	at android.os.Parcel.readException(Parcel.java:2004)
02-12 06:19:36.803  3005  3367 W DocumentsContract: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
02-12 06:19:36.803  3005  3367 W DocumentsContract: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
02-12 06:19:36.803  3005  3367 W DocumentsContract: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:651)
02-12 06:19:36.803  3005  3367 W DocumentsContract: 	at android.content.ContentProviderClient.call(ContentProviderClient.java:483)
02-12 06:19:36.803  3005  3367 W DocumentsContract: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1172)
02-12 06:19:36.803  3005  3367 W DocumentsContract: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1154)
02-12 06:19:36.803  3005  3367 W DocumentsContract: 	at com.hippo.unifile.DocumentsContractApi21.createFile(DocumentsContractApi21.java:56)
02-12 06:19:36.803  3005  3367 W DocumentsContract: 	at com.hippo.unifile.DocumentsContractApi21.createDirectory(DocumentsContractApi21.java:66)
02-12 06:19:36.803  3005  3367 W DocumentsContract: 	at com.hippo.unifile.TreeDocumentFile.createDirectory(TreeDocumentFile.java:104)
02-12 06:19:36.803  3005  3367 W DocumentsContract: 	at eu.kanade.tachiyomi.data.backup.BackupCreateService.createBackupFromApp(BackupCreateService.kt:118)
02-12 06:19:36.803  3005  3367 W DocumentsContract: 	at eu.kanade.tachiyomi.data.backup.BackupCreateService.onHandleIntent(BackupCreateService.kt:74)
02-12 06:19:36.803  3005  3367 W DocumentsContract: 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)
02-12 06:19:36.803  3005  3367 W DocumentsContract: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-12 06:19:36.803  3005  3367 W DocumentsContract: 	at android.os.Looper.loop(Looper.java:164)
02-12 06:19:36.803  3005  3367 W DocumentsContract: 	at android.os.HandlerThread.run(HandlerThread.java:65)
02-12 06:19:36.803  3005  3367 E DocumentsContractApi21: Failed to createFile
02-12 06:19:36.803  3005  3367 E DocumentsContractApi21: java.lang.SecurityException: Permission Denial: writing com.android.externalstorage.ExternalStorageProvider uri content://com.android.externalstorage.documents/tree/primary%3ATachiyomi%2Fbackup/document/primary%3ATachiyomi%2Fbackup from pid=3005, uid=10173 requires android.permission.MANAGE_DOCUMENTS, or grantUriPermission()
02-12 06:19:36.803  3005  3367 E DocumentsContractApi21: 	at android.os.Parcel.readException(Parcel.java:2004)
02-12 06:19:36.803  3005  3367 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
02-12 06:19:36.803  3005  3367 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
02-12 06:19:36.803  3005  3367 E DocumentsContractApi21: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:651)
02-12 06:19:36.803  3005  3367 E DocumentsContractApi21: 	at android.content.ContentProviderClient.call(ContentProviderClient.java:483)
02-12 06:19:36.803  3005  3367 E DocumentsContractApi21: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1172)
02-12 06:19:36.803  3005  3367 E DocumentsContractApi21: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1154)
02-12 06:19:36.803  3005  3367 E DocumentsContractApi21: 	at com.hippo.unifile.DocumentsContractApi21.createFile(DocumentsContractApi21.java:56)
02-12 06:19:36.803  3005  3367 E DocumentsContractApi21: 	at com.hippo.unifile.DocumentsContractApi21.createDirectory(DocumentsContractApi21.java:66)
02-12 06:19:36.803  3005  3367 E DocumentsContractApi21: 	at com.hippo.unifile.TreeDocumentFile.createDirectory(TreeDocumentFile.java:104)
02-12 06:19:36.803  3005  3367 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.backup.BackupCreateService.createBackupFromApp(BackupCreateService.kt:118)
02-12 06:19:36.803  3005  3367 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.backup.BackupCreateService.onHandleIntent(BackupCreateService.kt:74)
02-12 06:19:36.803  3005  3367 E DocumentsContractApi21: 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)
02-12 06:19:36.803  3005  3367 E DocumentsContractApi21: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-12 06:19:36.803  3005  3367 E DocumentsContractApi21: 	at android.os.Looper.loop(Looper.java:164)
02-12 06:19:36.803  3005  3367 E DocumentsContractApi21: 	at android.os.HandlerThread.run(HandlerThread.java:65)
```

Tachiyomi only requests Storage runtime permission which i have granted to the app, so this seems weird to me.

**Comment by paulo27ms** [comment]
I am on Android 4.1.2 and it hasn't been fixed either.

**Comment by paulo27ms** [comment]
For me, on Android 4.1.2, they stopped working months ago on the stable builds and I believe they have "fixed " it already, but on 0.6.8 they still don't work.
But on the dev build (r1343) it seems to be working. I wonder if it's a library issue since I don't have the same on both apps, but no clue.

**Comment by inorichi** [comment]
@tippl Did you use an app like Titanium to restore the application's data?

**Comment by tippl** [comment]
@inorichi Not sure right now. Don't use apps like Titanium, but i recently had to reset my phone and Tachi data might have been caried over by Google's app cloud backup. Not sure if it backs up non play store apps or if it did for Tachi though.

**Comment by tippl** [comment]
@NoodleMage Why was this issue closed?

**Comment by NoodleMage** [comment]
I have no idea. Sorry misclicked I think :O

**Comment by inorichi** [comment]
Try to change the directory of backups, even if set to the same one. It just probably needs the permissions of SAF.

**Comment by tippl** [comment]
@inorichi Changed directory to a different one and back. After focing job execution with open app it now backs up. All that needs to be fixed now is the backup service starting to follow 8.0 requirements so that it can back up without app being open.

**Comment by inorichi** [comment]
They should work just fine? Background execution limits restricts you from launching a non-foreground service if it was put in background, but the JobScheduler should be waking the app, although we're using it to launch another background service and that might be the reason.

**Comment by tippl** [comment]
From my testing backups only happen when the app is open and in foreground or during the grace period after it goes to background.

The problem is when the app is not open. Desired functionality would be the app backs up even if the app is not foreground.

I believe `startForegroundService` and `startForeground` should be used here too, like it's done in the library update service. It would however require a notification for when the service is running.

**Comment by inorichi** [comment]
@tippl Note that not even a foreground service will help if the app was killed. Scheduling of jobs is up to the system, which should be the one waking up the app when required.

Also, the backup service is fast unlike the library update and should have finished before it's sent to background again.

**Comment by tippl** [comment]
@inorichi Not sure what you mean by the app being killed. If you mean app being removed from the recents menu, then scheduled jobs still work even with the app not running. (see library updates still working)

The backup service is fast, that would mean it can probably finish before the need for the app to show notification as a foreground service kills it.

However when the job scheduler attempts to start the service it is not allowed to start at all, speed of the backup is irrelevant when the backup doesn't run at all. (see my second comment here `JobExecutor: java.lang.IllegalStateException: Not allowed to start service Intent`)

Feel free to redo my tests:
Get an api 27 avd machine.
`adb shell dumpsys jobscheduler` to see currently scheduled jobs
`adb shell cmd jobscheduler run -f eu.kanade.tachiyomi <id>` with id being the numeric job id found in previous command to force execution of the job

When the second command is run, a backup file is only created when the application is in focus or was closed a while ago. When the app is background or removed from recents no files are created.

Contrary to this, forcing execution of the library update job works even if the app is background or not running at all.

Having a foreground service running makes the app foreground, so if the timing is right and the backup service runs during a library update it is allowed to run, which would probably explain that sometimes the app manages to backup.

**Comment by inorichi** [comment]
You're totally right. I wasn't paying attention to that exception!

Anyways, the solution won't be a foreground service, but just perform the task in the given method `onRunJob`. We just have to extract the backup creation function outside the service.

**Comment by inorichi** [comment]
Should be working now on Oreo.
