### ISSUE TITLE
Unknown exception found!

### ISSUE THREAD

**Issue by dbesch** [inorichi/tachiyomi#1282]
When doing a fdroid update I get this error.

Unknown exception found!
Traceback (most recent call last):
  File "/usr/bin/fdroid", line 115, in <module>
    main()
  File "/usr/bin/fdroid", line 93, in main
    mod.main()
  File "/usr/lib/python2.7/dist-packages/fdroidserver/update.py", line 1127, in main
    apks, cc = scan_apks(apps, apkcache, repodirs[0], knownapks)
  File "/usr/lib/python2.7/dist-packages/fdroidserver/update.py", line 552, in scan_apks
    dt_obj = datetime(*info.date_time)
ValueError: month must be in 1..12

**Comment by inorichi** [comment]
That exception is unrelated to tachiyomi. I can't help you there.
