### ISSUE TITLE
Reader buttons not working

### ISSUE THREAD

**Issue by j2ghz** [inorichi/tachiyomi#214]
Reader buttons don't work, they return to library. The 3-dot menu works. Logcat empty.

---
Version: r552 and v0.1.4
**OS: Remix OS, Android X86, 5.1.1**

**Comment by j2ghz** [comment]
```
exceptionClassName: java.lang.IllegalArgumentException
exceptionMessage: View=com.android.internal.policy.impl.PhoneWindow$DecorView{e678d1c V.E..... ......I. 0,0-1920,1044} not attached to window manager
throwFileName: WindowManagerGlobal.java
throwClassName: android.view.WindowManagerGlobal
throwMethodName: findViewLocked
throwLineNumber: 439
stackTrace: java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{e678d1c V.E..... ......I. 0,0-1920,1044} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:439)
	at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:322)
	at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:96)
	at eu.kanade.tachiyomi.ui.reader.ReaderMenu.showImmersiveDialog(ReaderMenu.java:276)
	at eu.kanade.tachiyomi.ui.reader.ReaderMenu.lambda$initializeMenu$55(ReaderMenu.java:228)
	at eu.kanade.tachiyomi.ui.reader.ReaderMenu.access$lambda$4(ReaderMenu.java)
	at eu.kanade.tachiyomi.ui.reader.ReaderMenu$$Lambda$5.onClick(Unknown Source)
	at android.view.View.performClick(View.java:4828)
	at android.view.View$PerformClick.run(View.java:20225)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5401)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by inorichi** [comment]
It has to do with a solution to not leave immersive mode: http://stackoverflow.com/questions/22794049/how-to-maintain-the-immersive-mode-in-dialogs/23207365

Guess I should try another one.

**Comment by j2ghz** [comment]
Immersive mode = Hide status bar?

**Comment by inorichi** [comment]
And navigation bar, for devices without physical buttons.

**Comment by inorichi** [comment]
Can you confirm?

**Comment by j2ghz** [comment]
It works.
