### ISSUE TITLE
[Bug] Latest dev versions crash on Android 4.x

### ISSUE THREAD

**Issue by arkon** [inorichi/tachiyomi#2436]
Logcat from API 19 (KitKat) emulator:

```
01-05 15:11:39.926 4187-4205/? E/AndroidRuntime: FATAL EXCEPTION: RxComputationScheduler-2
    Process: eu.kanade.tachiyomi.debug:acra, PID: 4187
    java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
     Caused by: java.lang.ExceptionInInitializerError
        at okhttp3.internal.platform.Platform$Companion.findPlatform(Platform.kt:211)
        at okhttp3.internal.platform.Platform$Companion.access$findPlatform(Platform.kt:179)
        at okhttp3.internal.platform.Platform.<clinit>(Platform.kt:180)
        at okhttp3.internal.tls.CertificateChainCleaner$Companion.get(CertificateChainCleaner.kt:42)
        at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.kt:728)
        at eu.kanade.tachiyomi.network.NetworkHelper.enableTLS12(NetworkHelper.kt:100)
        at eu.kanade.tachiyomi.network.NetworkHelper.<init>(NetworkHelper.kt:27)
        at eu.kanade.tachiyomi.AppModule$registerInjectables$5.invoke(AppModule.kt:32)
        at eu.kanade.tachiyomi.AppModule$registerInjectables$5.invoke(AppModule.kt:18)
        at uy.kohesive.injekt.registry.default.DefaultRegistrar$addSingletonFactory$1$$special$$inlined$getOrPut$lambda$1.invoke(DefaultRegistrar.kt:49)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at uy.kohesive.injekt.registry.default.DefaultRegistrar$addSingletonFactory$1.invoke(DefaultRegistrar.kt:173)
        at uy.kohesive.injekt.registry.default.DefaultRegistrar.getInstance(DefaultRegistrar.kt:103)
        at eu.kanade.tachiyomi.AppModule$registerInjectables$12.invoke(AppModule.kt:64)
        at eu.kanade.tachiyomi.AppModule$registerInjectables$12.invoke(AppModule.kt:18)
        at eu.kanade.tachiyomi.AppModule$rxAsync$1.call(AppModule.kt:59)
        at eu.kanade.tachiyomi.AppModule$rxAsync$1.call(AppModule.kt:18)
        at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
        at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
        at rx.Observable.unsafeSubscribe(Observable.java:10327)
        at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
        at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$1.call(EventLoopsScheduler.java:172)
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:841) 
     Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 19
        at okhttp3.internal.platform.AndroidPlatform.<clinit>(AndroidPlatform.kt:232)
        at okhttp3.internal.platform.Platform$Companion.findPlatform(Platform.kt:211) 
        at okhttp3.internal.platform.Platform$Companion.access$findPlatform(Platform.kt:179) 
        at okhttp3.internal.platform.Platform.<clinit>(Platform.kt:180) 
        at okhttp3.internal.tls.CertificateChainCleaner$Companion.get(CertificateChainCleaner.kt:42) 
        at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.kt:728) 
        at eu.kanade.tachiyomi.network.NetworkHelper.enableTLS12(NetworkHelper.kt:100) 
        at eu.kanade.tachiyomi.network.NetworkHelper.<init>(NetworkHelper.kt:27) 
        at eu.kanade.tachiyomi.AppModule$registerInjectables$5.invoke(AppModule.kt:32) 
        at eu.kanade.tachiyomi.AppModule$registerInjectables$5.invoke(AppModule.kt:18) 
        at uy.kohesive.injekt.registry.default.DefaultRegistrar$addSingletonFactory$1$$special$$inlined$getOrPut$lambda$1.invoke(DefaultRegistrar.kt:49) 
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) 
        at uy.kohesive.injekt.registry.default.DefaultRegistrar$addSingletonFactory$1.invoke(DefaultRegistrar.kt:173) 
        at uy.kohesive.injekt.registry.default.DefaultRegistrar.getInstance(DefaultRegistrar.kt:103) 
        at eu.kanade.tachiyomi.AppModule$registerInjectables$12.invoke(AppModule.kt:64) 
        at eu.kanade.tachiyomi.AppModule$registerInjectables$12.invoke(AppModule.kt:18) 
        at eu.kanade.tachiyomi.AppModule$rxAsync$1.call(AppModule.kt:59) 
        at eu.kanade.tachiyomi.AppModule$rxAsync$1.call(AppModule.kt:18) 
        at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48) 
        at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33) 
        at rx.Observable.unsafeSubscribe(Observable.java:10327) 
        at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100) 
        at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$1.call(EventLoopsScheduler.java:172) 
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:841) 
```

Oddly enough, it didn't crash in an API 16 (Jelly Bean) emulator.

This is due to OkHttp dropping support for Android 4.x: https://developer.squareup.com/blog/okhttp-3-13-requires-android-5/

But we require the new version of OkHttp to work in conjunction with the latest versions of Retrofit, which is required for AndroidX, which is required for the latest versions of the Android SDK.

**Comment by arkon** [comment]
We might have to finally drop support for Android 4.x.

**Comment by joseph619** [comment]
It's been a long ride, honestly though people should upgrade their device now, Android 4 is ancient history

**Comment by SnakeDoc83** [comment]
I imagine if people are using devices that old odds are that it's because upgrading would be a burden (financial or otherwise).

**Comment by arkon** [comment]
Android 4.4.4 is 5 years old, which isn't _that_ old. That said, those users can still use an older version of Tachiyomi (e.g. v0.8.4).

**Comment by MerradOklom** [comment]
This was something expected. I'm one of those few users with KitKat (I don't really want to specify the reasons I'm still using this old brick of a phone).
Dev version r1571 still works for me so I'll hold on to it as much as I can.

**Comment by 0klux** [comment]
Cam you give some general steps to reproduce this? I have latest dev on my Jellybean and it is working fine so far

**Comment by melnation-com** [comment]
> 
> 
> This was something expected. I'm one of those few users with KitKat (I don't really want to specify the reasons I'm still using this old brick of a phone).
> Dev version r1571 still works for me so I'll hold on to it as much as I can.

Is 1571 still the only one working for you? I also have 1571 but strangely, ever since Jan 8 I never got any updates from any manga other than Solo Leveling on Jan 16(UTC +8) just recently, Not sure it's a coincidence but I've got Bocu no Hero Academia, Dr. Stone, and Demon Slayer that had consistently gets updates every week(or atleast every other week), but now not from the 30+ mangas got an update except solo leveling

**Comment by MerradOklom** [comment]
> > This was something expected. I'm one of those few users with KitKat (I don't really want to specify the reasons I'm still using this old brick of a phone).
> > Dev version r1571 still works for me so I'll hold on to it as much as I can.
> 
> Is 1571 still the only one working for you? I also have 1571 but strangely, ever since Jan 8 I never got any updates from any manga other than Solo Leveling on Jan 16(UTC +8) just recently, Not sure it's a coincidence but I've got Bocu no Hero Academia, Dr. Stone, and Demon Slayer that had consistently gets updates every week(or atleast every other week), but now not from the 30+ mangas got an update except solo leveling.
> 
> Just incase. are you still using Android 4.4.#.. I was thinking of installing those 3rd party OS like Lineage, I don't think it supports 4.4.# that's why I'm looking.
> 
> I also heard of those Android requirement editors, to edit the Android requirement to the version u want. Tho I may not look like it but I frequent in mod forums.

It works just fine, I have had no problem so far. Maybe it has not been updated in the source you're using, try migrating to another one. I'm using the stock rom, never tried LineageOS so I'm afraid I can't help you with that, what I do know is that, although you can change the mininum sdk of an apk with some specialized app (like Apk Editor) it doesn't guarantee it would work, also in the newer dev versions everything that made the app compatible with Android 4.4.x was removed.

**Comment by melnation-com** [comment]
> 
> 
> > > This was something expected. I'm one of those few users with KitKat (I don't really want to specify the reasons I'm still using this old brick of a phone).
> > > Dev version r1571 still works for me so I'll hold on to it as much as I can.
> > 
> > 
> > Is 1571 still the only one working for you? I also have 1571 but strangely, ever since Jan 8 I never got any updates from any manga other than Solo Leveling on Jan 16(UTC +8) just recently, Not sure it's a coincidence but I've got Bocu no Hero Academia, Dr. Stone, and Demon Slayer that had consistently gets updates every week(or atleast every other week), but now not from the 30+ mangas got an update except solo leveling.
> > Just incase. are you still using Android 4.4.#.. I was thinking of installing those 3rd party OS like Lineage, I don't think it supports 4.4.# that's why I'm looking.
> > I also heard of those Android requirement editors, to edit the Android requirement to the version u want. Tho I may not look like it but I frequent in mod forums.
> 
> It works just fine, I have had no problem so far. Maybe it has not been updated in the source you're using, try migrating to another one. I'm using the stock rom, never tried LineageOS so I'm afraid I can't help you with that, what I do know is that, although you can change the mininum sdk of an apk with some specialized app (like Apk Editor) it doesn't guarantee it would work, also in the newer dev versions everything that made the app compatible with Android 4.4.x was removed.

Everything is working so far, got the updates a few days after I posted. Is 1571 still the only one working for you?

As a sign of appreciation, I suggest this manga Uzaki-chan wa Asobitai! I personally sourced from mangasee but u can source from anywhere u like.

**Comment by melnation-com** [comment]
> 
> 
> This was something expected. I'm one of those few users with KitKat (I don't really want to specify the reasons I'm still using this old brick of a phone).
> Dev version r1571 still works for me so I'll hold on to it as much as I can.

Is r1571 still the only one working for you?

**Comment by CarlosEsco** [comment]
you can use 8.5  its the last stable/dev build that will work with android 4.x

**Comment by Ryogo-Z** [comment]
That is really sad since there are still a lot of e-ink readers running android 4.4. Hell, many of those readers still sold in stores (Nook Glowlight 3, any Tolino reader).
I hope 0.85 build will last long enough...

**Comment by CarlosEsco** [comment]
Yea it sucks ereadee companies are slacking

**Comment by mirh** [comment]
> But we require the new version of OkHttp to work in conjunction with the latest versions of Retrofit, which is required for AndroidX, which is required for the latest versions of the Android SDK.

I'm sorry for being late to the party, and maybe still missing something..

But while I could indeed find that Retrofit 2.7x needs OkHttp >3.12 
And that AndroidX is kind-of-heavily-recommended in newer SDKs (even though perhaps not literally enforced)

I'm missing the Retrofit-AndroidX link. In fact [word of god](https://github.com/square/retrofit/issues/3179) seemed to rule out that. Did you mean coroutines perhaps?
They should be supported in the [2.6 branch](https://github.com/square/retrofit/tree/two-six), which is still being maintained and doesn't seem to lack anything important.

**Comment by arkon** [comment]
To be honest, I don't actually remember. Maybe the build failures I was having at the time were unrelated, but I'm not looking back at this point either considering Android 4.x users account for ~1.3% of total users and introduces other headaches beyond just Retrofit/OkHttp.

**Comment by mirh** [comment]
I would guess because J2K had just updated okhttp to the latest version available at the time without restraints, and period. But it wasn't mandatory for newer retrofit. 

Well, so much for my tolino 🇫

**Comment by arkon** [comment]
I'm pretty sure the J2K fork dropped 4.x support way before the main app did though.

**Comment by mirh** [comment]
Yes, and #2424 inadvertently pulled in some of those assumptions.
