### ISSUE TITLE
[Bug] Webview crashes in Android 5.x

### ISSUE THREAD

**Issue by arkon** [inorichi/tachiyomi#2437]
### Device information
* Tachiyomi version: dev, post-AndroidX migration
* Android version: 5.x

## Steps to reproduce
1. Open any catalogue in webview

```
01-05 16:05:50.601 4610-4610/eu.kanade.tachiyomi.debug E/ACRA: ACRA caught a InflateException for eu.kanade.tachiyomi.debug
    android.view.InflateException: Binary XML file line #2: Error inflating class android.webkit.WebView
        at android.view.LayoutInflater.createView(LayoutInflater.java:633)
        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
        at eu.kanade.tachiyomi.ui.manga.info.MangaWebViewController.inflateView(MangaWebViewController.kt:27)
        at eu.kanade.tachiyomi.ui.base.controller.BaseController.onCreateView(BaseController.kt:48)
        at com.bluelinelabs.conductor.RestoreViewOnCreateController.onCreateView(RestoreViewOnCreateController.java:35)
        at com.bluelinelabs.conductor.Controller.inflate(Controller.java:1012)
        at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:190)
        at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:154)
        at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:813)
        at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:783)
        at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:765)
        at com.bluelinelabs.conductor.Router.pushController(Router.java:182)
        at eu.kanade.tachiyomi.ui.catalogue.browse.BrowseCatalogueController.openInWebView(BrowseCatalogueController.kt:298)
        at eu.kanade.tachiyomi.ui.catalogue.browse.BrowseCatalogueController.onOptionsItemSelected(BrowseCatalogueController.kt:283)
        at com.bluelinelabs.conductor.Controller.optionsItemSelected(Controller.java:1313)
        at com.bluelinelabs.conductor.Router.onOptionsItemSelected(Router.java:669)
        at com.bluelinelabs.conductor.internal.LifecycleHandler.onOptionsItemSelected(LifecycleHandler.java:272)
        at android.app.Fragment.performOptionsItemSelected(Fragment.java:2159)
        at android.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:1988)
        at android.app.Activity.onMenuItemSelected(Activity.java:2885)
        at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:384)
        at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:219)
        at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)
        at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
        at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
        at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
        at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
        at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
        at android.widget.AdapterView.performItemClick(AdapterView.java:300)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1143)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3044)
        at android.widget.AbsListView$3.run(AbsListView.java:3833)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5221)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by arkon** [comment]
This is a bug with `androidx.appcompat:appcompat:1.1.0`: https://issuetracker.google.com/issues/141132133
