### ISSUE TITLE
[Bug] Komga : Failed to open dialog-text on settings

### ISSUE THREAD

**Issue by pedrotk** [inorichi/tachiyomi#2513]
### Device information
* Tachiyomi extension version: 1.2.6
* Tachiyomi version: r1640
* Android version: 9

## Steps to reproduce
1. Open Komga (all) Extension Config
2. Click on any settings (address, username, password)

### Expected behavior
Should be open the dialog-text

### Actual behavior
Crash tachiyomi

### Other details
Probably the problem is about with androidx dialog.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.widget.EditText.requestFocus()' on a null object reference
	at androidx.preference.EditTextPreferenceDialogController.onBindDialogView(EditTextPreferenceDialogController.java:67)
	at androidx.preference.PreferenceDialogController.onCreateDialog(PreferenceDialogController.java:179)
	at androidx.preference.PreferenceDialogController.onCreateView(PreferenceDialogController.java:87)
	at com.bluelinelabs.conductor.RestoreViewOnCreateController.onCreateView(RestoreViewOnCreateController.java:35)
	at com.bluelinelabs.conductor.Controller.inflate(Controller.java:1012)
	at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:190)
	at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:154)
	at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:813)
	at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:783)
	at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:765)
	at com.bluelinelabs.conductor.Router.pushController(Router.java:182)
	at androidx.preference.PreferenceDialogController.showDialog(PreferenceDialogController.java:241)
	at androidx.preference.PreferenceDialogController.showDialog(PreferenceDialogController.java:230)
	at eu.kanade.tachiyomi.ui.extension.ExtensionDetailsController.onDisplayPreferenceDialog(ExtensionDetailsController.kt:180)
	at androidx.preference.PreferenceManager.showDialog(PreferenceManager.java:537)
	at androidx.preference.DialogPreference.onClick(DialogPreference.java:257)
	at androidx.preference.Preference.performClick(Preference.java:1182)
	at androidx.preference.Preference.performClick(Preference.java:1166)
	at androidx.preference.Preference$1.onClick(Preference.java:181)
	at android.view.View.performClick(View.java:7333)
	at android.view.View.performClickInternal(View.java:7299)
	at android.view.View.access$3200(View.java:846)
	at android.view.View$PerformClick.run(View.java:27773)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:6990)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

**Comment by gotson** [comment]
Hi @arkon, is this something related to the extension, or more to the development build of Tachiyomi?

**Comment by arkon** [comment]
It's an issue with [conductor-support-preference](https://github.com/inorichi/conductor-support-preference) and how the `EditTextPreference` has changed in AndroidX, but I haven't yet figured out how to make it work properly.
