### ISSUE TITLE
[Bug] Crashes related to filters

### ISSUE THREAD

**Issue by RealKC** [inorichi/tachiyomi#3568]
### Device information
- Tachiyomi version: 0.10.1
- Android version: 10

### Source information
- Name: HBrowse
- Extension version: 1.2.2

## Steps to reproduce
A. First crash
1. Click on the "Filter" button inside the HBrowse source
2. Open "Genre", "Type", "Setting", "Fetish", "Role"
3. Close "Role"

I believe this can be reproduced with any 5 consecutive sources. (but don't quote me on that)

B. Second crash
1. Click on the "Filter" button inside the HBrowse source
2. Open "Fetish"
3. Open "Relationship"
4. Close "Relationship"

### Expected behavior
The filters should've closed

### Actual behavior
Tachiyomi crashed

**Comment by arkon** [comment]
```
2020-08-02 10:41:40.906 7717-7717/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: eu.kanade.tachiyomi.debug, PID: 7717
    java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 186(offset:180).state:187 androidx.recyclerview.widget.RecyclerView{45b31c VFED..... ......ID 0,0-1080,1929}, adapter:eu.davidea.flexibleadapter.FlexibleAdapter@6050ed8, layout:androidx.recyclerview.widget.LinearLayoutManager@dbd5231, context:eu.kanade.tachiyomi.ui.main.MainActivity@aee8df3
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6345)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6281)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6277)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4223)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3978)
        at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1996)
        at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:416)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1163)
        at android.view.Choreographer.doCallbacks(Choreographer.java:986)
        at android.view.Choreographer.doFrame(Choreographer.java:894)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1148)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7697)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```
