### ISSUE TITLE
[Bug] Tachiyomi keeps stopping on my device

### ISSUE THREAD

**Issue by Igorskie** [inorichi/tachiyomi#3833]
## Device information
* Tachiyomi version: v0.10.5
* Android version: Android 10
* Device: Poco X3 NFC

## Steps to reproduce
1. Fresh install of Tachiyomi
2. Open Tachiyomi

### Expected behavior
The app launches with no problems and directed to library

### Actual behavior
Tachiyomi automatically closes on launch

### Other details
I think I've pretty much tried everything I had in mind. Also there's no cache or app data to clear because it is a fresh install of Tachiyomi. I've tried reinstalling it many times but to no avail.

**Comment by arkon** [comment]
Please provide crash logs if possible.

Potential ways of getting them:

- https://help.getpocket.com/article/1073-retrieving-a-pocket-crash-log-on-android
- https://play.google.com/store/apps/details?id=com.dp.logcatapp&hl=en_CA

**Comment by Igorskie** [comment]
Here's the crash log file that I copied from Logcat. I'm sorry for just pasting it here, I don't know where's the attatch file option in mobile view.

Also, I installed the preview version and it actually worked. Didn't encounter any problems so far. 
FATAL EXCEPTION: main
Process: eu.kanade.tachiyomi, PID: 29221
java.lang.ExceptionInInitializerError
	at eu.kanade.tachiyomi.ui.base.activity.BaseActivity.<init>(BaseActivity.kt:7)
	at eu.kanade.tachiyomi.ui.main.MainActivity.<init>(MainActivity.kt:1)
	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:1)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1251)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3225)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3462)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2049)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7565)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: uy.kohesive.injekt.api.InjektionException: No registered instance or factory for type class eu.kanade.tachiyomi.data.preference.PreferencesHelper
	at uy.kohesive.injekt.registry.default.DefaultRegistrar.getInstance(DefaultRegistrar.kt:3)
	at uy.kohesive.injekt.api.InjektScope.getInstance(Unknown Source:7)
	at eu.kanade.tachiyomi.util.system.LocaleHelper$$special$$inlined$injectLazy$1.invoke(Injekt.kt:3)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:6)
	at eu.kanade.tachiyomi.util.system.LocaleHelper.getPreferences(Unknown Source:2)
	at eu.kanade.tachiyomi.util.system.LocaleHelper.<clinit>(LocaleHelper.kt:3)
	... 18 more

**Comment by Igorskie** [comment]
Here's the crash log file that I copied from Logcat. I'm sorry for just pasting it here, I don't know where's the attatch file option in mobile view.

Also, I installed the preview version and it actually worked. Didn't encounter any problems so far.

Here's the crash log file that I copied from Logcat. I'm sorry for just pasting it here, I don't know where's the attatch file option in mobile view.

**Comment by Igorskie** [comment]
### Update

For some reason that I don't know, the stable version finally worked.

**Comment by arkon** [comment]
¯\\\_(ツ)_/¯ 

Sample:
```
[09-23 05:41:41.355 29221:29221 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: eu.kanade.tachiyomi, PID: 29221
java.lang.ExceptionInInitializerError
	at eu.kanade.tachiyomi.ui.base.activity.BaseActivity.<init>(BaseActivity.kt:7)
	at eu.kanade.tachiyomi.ui.main.MainActivity.<init>(MainActivity.kt:1)
	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:1)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1251)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3225)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3462)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2049)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7565)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: uy.kohesive.injekt.api.InjektionException: No registered instance or factory for type class eu.kanade.tachiyomi.data.preference.PreferencesHelper
	at uy.kohesive.injekt.registry.default.DefaultRegistrar.getInstance(DefaultRegistrar.kt:3)
	at uy.kohesive.injekt.api.InjektScope.getInstance(Unknown Source:7)
	at eu.kanade.tachiyomi.util.system.LocaleHelper$$special$$inlined$injectLazy$1.invoke(Injekt.kt:3)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:6)
	at eu.kanade.tachiyomi.util.system.LocaleHelper.getPreferences(Unknown Source:2)
	at eu.kanade.tachiyomi.util.system.LocaleHelper.<clinit>(LocaleHelper.kt:3)
	... 18 more
```

Not sure why it'd ever fail to instantiate the modules properly.
