### ISSUE TITLE
Extension downloading but not installing 

### ISSUE THREAD

**Issue by oge2k** [inorichi/tachiyomi#3842]
App version:
0.10.5 and former versions up to version 0.9.2
Android version:
7.0
Phone:
Vernee thor E
Issue/Request:
Can download extensions but there is an error while installing 

Try to download extension
Extension Downloads
Android opens installer and gives error message about error while parsing package

Other details:
Also does not work when updating extensions 
I do not use VPN .
Downloading and installing extensions directly from tachiyomi site works fine(got link from discord) .
![Screenshot_20200924-234750](https://user-images.githubusercontent.com/46646966/94208154-199bb700-fec1-11ea-8bea-6314e3495131.png)

**Comment by arkon** [comment]
Try using https://play.google.com/store/apps/details?id=com.aefyr.sai

**Comment by oge2k** [comment]
Done what next

**Comment by oge2k** [comment]
Done what next

**Comment by arkon** [comment]
Try installing an extension APK and see what the error is.

**Comment by oge2k** [comment]
Still the same

**Comment by oge2k** [comment]
If it is from the tachiyomi it is the same error but if it is for the other application how do i install the extension using it

**Comment by arkon** [comment]
Download from https://tachiyomi.org/extensions/

**Comment by oge2k** [comment]
Rootless installer error:

 java.lang.IllegalArgumentException: ZIP doesn't contain any apk files
	at com.aefyr.sai.model.apksource.ZipApkSource.nextApk(ZipApkSource.java:58)
	at com.aefyr.sai.model.apksource.CopyToFileApkSource.nextApk(CopyToFileApkSource.java:33)
	at com.aefyr.sai.installer.rootless.RootlessSAIPackageInstaller.installApkFiles(RootlessSAIPackageInstaller.java:88)
	at com.aefyr.sai.installer.SAIPackageInstaller.lambda$processQueue$0$SAIPackageInstaller(SAIPackageInstaller.java:90)
	at com.aefyr.sai.installer.-$$Lambda$SAIPackageInstaller$6hKMtxaB1Yqc0HYKOE26UUOnkTo.run(lambda)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

**Comment by oge2k** [comment]
It installed without an error

**Comment by oge2k** [comment]
Or will the app soon stop being used on Android 7

**Comment by arkon** [comment]
No, Android 5+ is still supported.

This is likely just an issue with your phone.

**Comment by oge2k** [comment]
just to say there was something on the version 0.8.5 that allowed download and installation of extensions through the application, maybe there is something there that fixes this issue
