### ISSUE TITLE
[Bug] <app wont open and crashes everytime i try to use it>

### ISSUE THREAD

**Issue by sexyasianboi** [inorichi/tachiyomi#3973]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.10.5)
- I have updated all extensions
- If this is an issue with an extension, that I should be opening an issue in https://github.com/inorichi/tachiyomi-extensions

**DELETE THIS SECTION IF YOU HAVE READ AND ACKNOWLEDGED IT**

---

## Device information
* Tachiyomi version: 10.5
* Android version: 10
* Device: moto g7 ower

## Steps to reproduce
1. First step i went to open it it acts like it was working and then it crashes and wont open at all
2. Second step i have rebooted my device thinking it might fix it but it didnt fix it 

### Expected behavior
This should happen.
it should have opened and allowed me to read my mangas
### Actual behavior
This happened instead.
it wont open and just crashes everytime i try to open it
[manga app crash bug.zip](https://github.com/inorichi/tachiyomi/files/5435802/manga.app.crash.bug.zip)

## Other details
Additional details and attachments.[manga app crash bug.zip](https://github.com/inorichi/tachiyomi/files/5435802/manga.app.crash.bug.zip)

**Comment by arkon** [comment]
```
10-25 12:54:28.868 10209  5096  5170 E ACRA    : ACRA caught a AndroidRuntimeException for eu.kanade.tachiyomi
10-25 12:54:28.868 10209  5096  5170 E ACRA    : android.util.AndroidRuntimeException: java.lang.reflect.InvocationTargetException
10-25 12:54:28.868 10209  5096  5170 E ACRA    : 	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:271)
10-25 12:54:28.868 10209  5096  5170 E ACRA    : 	at android.webkit.CookieManager.getInstance(CookieManager.java:47)
10-25 12:54:28.868 10209  5096  5170 E ACRA    : 	at eu.kanade.tachiyomi.network.AndroidCookieJar.<init>(AndroidCookieJar.kt:2)
10-25 12:54:28.868 10209  5096  5170 E ACRA    : 	at eu.kanade.tachiyomi.network.NetworkHelper.<init>(NetworkHelper.kt:5)
10-25 12:54:28.868 10209  5096  5170 E ACRA    : 	at eu.kanade.tachiyomi.AppModule$registerInjectables$5.invoke(AppModule.kt:2)
10-25 12:54:28.868 10209  5096  5170 E ACRA    : 	at eu.kanade.tachiyomi.AppModule$registerInjectables$5.invoke(AppModule.kt:1)
10-25 12:54:28.868 10209  5096  5170 E ACRA    : 	at uy.kohesive.injekt.registry.default.DefaultRegistrar$addSingletonFactory$1$$special$$inlined$getOrPut$lambda$1.invoke(DefaultRegistrar.kt:1)
10-25 12:54:28.868 10209  5096  5170 E ACRA    : 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:6)
10-25 12:54:28.868 10209  5096  5170 E ACRA    : 	at uy.kohesive.injekt.registry.default.DefaultRegistrar$addSingletonFactory$1.invoke(DefaultRegistrar.kt:4)
10-25 12:54:28.868 10209  5096  5170 E ACRA    : 	at uy.kohesive.injekt.registry.default.DefaultRegistrar.getInstance(DefaultRegistrar.kt:2)
10-25 12:54:28.868 10209  5096  5170 E ACRA    : 	at eu.kanade.tachiyomi.AppModule$registerInjectables$12.invokeSuspend(AppModule.kt:3)
10-25 12:54:28.868 10209  5096  5170 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
10-25 12:54:28.868 10209  5096  5170 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
10-25 12:54:28.868 10209  5096  5170 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
10-25 12:54:28.868 10209  5096  5170 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
10-25 12:54:28.868 10209  5096  5170 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
10-25 12:54:28.868 10209  5096  5170 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)
10-25 12:54:28.868 10209  5096  5170 E ACRA    : Caused by: java.lang.reflect.InvocationTargetException
10-25 12:54:28.868 10209  5096  5170 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
10-25 12:54:28.868 10209  5096  5170 E ACRA    : 	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:266)
10-25 12:54:28.868 10209  5096  5170 E ACRA    : 	... 16 more
10-25 12:54:28.868 10209  5096  5170 E ACRA    : Caused by: TH: errorCode=2
10-25 12:54:28.868 10209  5096  5170 E ACRA    : 	at QH.g(chromium-SystemWebViewGoogle.aab-stable-424011400:22)
10-25 12:54:28.868 10209  5096  5170 E ACRA    : 	at QH.i(chromium-SystemWebViewGoogle.aab-stable-424011400:5)
10-25 12:54:28.868 10209  5096  5170 E ACRA    : 	at org.chromium.android_webview.AwBrowserProcess.h(chromium-SystemWebViewGoogle.aab-stable-424011400:9)
10-25 12:54:28.868 10209  5096  5170 E ACRA    : 	at com.android.webview.chromium.WebViewChromiumFactoryProvider.f(chromium-SystemWebViewGoogle.aab-stable-424011400:78)
10-25 12:54:28.868 10209  5096  5170 E ACRA    : 	at com.android.webview.chromium.WebViewChromiumFactoryProvider.<init>(chromium-SystemWebViewGoogle.aab-stable-424011400:12)
10-25 12:54:28.868 10209  5096  5170 E ACRA    : 	at com.android.webview.chromium.WebViewChromiumFactoryProviderForQ.<init>(chromium-SystemWebViewGoogle.aab-stable-424011400:1)
10-25 12:54:28.868 10209  5096  5170 E ACRA    : 	at com.android.webview.chromium.WebViewChromiumFactoryProviderForQ.create(chromium-SystemWebViewGoogle.aab-stable-424011400:1)
10-25 12:54:28.868 10209  5096  5170 E ACRA    : 	... 18 more
10-25 12:54:28.868 10209  5096  5170 E ACRA    : Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.google.android.webview-MM5QsFv2oukLct02OQPZzA==/lib/arm/libwebviewchromium.so" is 32-bit instead of 64-bit
10-25 12:54:28.868 10209  5096  5170 E ACRA    : 	at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
10-25 12:54:28.868 10209  5096  5170 E ACRA    : 	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
10-25 12:54:28.868 10209  5096  5170 E ACRA    : 	at java.lang.System.loadLibrary(System.java:1667)
10-25 12:54:28.868 10209  5096  5170 E ACRA    : 	at QH.g(chromium-SystemWebViewGoogle.aab-stable-424011400:14)
10-25 12:54:28.868 10209  5096  5170 E ACRA    : 	... 24 more
```

Make sure you have Webview installed/enabled/updated.
